CREATE TABLE EMPLEADO(
Dni VARCHAR2(9) PRIMARY KEY,
Nombre VARCHAR2(20) NOT NULL,
Apellidos VARCHAR2(50) NOT NULL,
Dirección VARCHAR2(100) NOT NULL,
Ciudad VARCHAR2(30) NOT NULL,
Cod_Postal NUMBER(5) NOT NULL,
Fecha_Alta DATE NOT NULL,
Categoria VARCHAR2(15) NOT NULL,
Salario NUMBER (5,2) NOT NULL 
);

CREATE TABLE CAMAREROS(
Id_Camarero VARCHAR2(9) NOT NULL PRIMARY KEY,
Turno VARCHAR2(10) NOT NULL,
Años_Exp NUMBER(2) NOT NULL,
CONSTRAINT FK_ID_CAMARERO FOREIGN KEY (Id_Camarero) REFERENCES EMPLEADO(Dni)
);

CREATE TABLE COCINEROS(
Id_Cocinero VARCHAR2(9) NOT NULL PRIMARY KEY,
Puesto VARCHAR2(15) NOT NULL,
Especialidad VARCHAR2(25) NOT NULL,
CONSTRAINT FK_ID_COCINERO FOREIGN KEY (Id_Cocinero) REFERENCES EMPLEADO(Dni)
);

CREATE TABLE ADMINISTRACION(
Id_Administracion VARCHAR2(9) NOT NULL PRIMARY KEY,
Cargo VARCHAR2(20) NOT NULL,
CONSTRAINT FK_ID_ADMINISTRACION FOREIGN KEY (Id_Administracion) REFERENCES EMPLEADO(Dni)
);

CREATE TABLE ENCARGADO(
Id_Encargado VARCHAR2(9) NOT NULL PRIMARY KEY,
Turno VARCHAR2(10) NOT NULL,
Años_Exp NUMBER(2) NOT NULL,
CONSTRAINT FK_ID_ENCARGADO FOREIGN KEY (Id_Encargado) REFERENCES EMPLEADO(Dni)
);

CREATE TABLE AYUDANTES(
Id_Ayudante VARCHAR2 (9) NOT NULL PRIMARY KEY,
CONSTRAINT FK_ID_AYUDANTE FOREIGN KEY (Id_Ayudante) REFERENCES EMPLEADO(Dni)
);

CREATE TABLE ENCARGADO_CAMARERO(
Id_Camarero VARCHAR2(9) NOT NULL,
Id_Encargado VARCHAR2(9) NOT NULL,
CONSTRAINT FK_CAMARERO FOREIGN KEY (Id_Camarero) REFERENCES CAMAREROS(Id_Camarero),
CONSTRAINT FK_ENCARGADO FOREIGN KEY (Id_Encargado) REFERENCES ENCARGADO(Id_Encargado)
);

CREATE TABLE COMEDOR(
Cod_Comedor VARCHAR2(3) PRIMARY KEY,
Nombre VARCHAR(15) NOT NULL,
Capac_Max NUMBER(3) NOT NULL,
Numero_Mesas NUMBER(2) NOT NULL,
Localizacion VARCHAR2(10) NOT NULL
);

CREATE TABLE RESERVA (
Num_Reserva NUMBER(10) PRIMARY KEY,
Fecha_Hora DATE NOT NULL,
Fecha_Hora_Comida DATE NOT NULL,
Tipo VARCHAR2(6) NOT NULL,
Num_Personas NUMBER(3) NOT NULL,
Tlfno_Contacto NUMBER(9) NOT NULL
);

CREATE TABLE MESAS (
Id_Mesa NUMBER(3) PRIMARY KEY,
Num_Asientos NUMBER(3) NOT NULL,
Cod_Comedor VARCHAR2(3) NOT NULL,
Id_Camarero VARCHAR2(9) NOT NULL,
Num_Reserva NUMBER(10) NOT NULL,
CONSTRAINT FK_CAMARERO_MESA FOREIGN KEY (Id_Camarero) REFERENCES CAMAREROS(Id_Camarero),
CONSTRAINT FK_COD_COMEDOR FOREIGN KEY (Cod_Comedor) REFERENCES COMEDOR(Cod_Comedor),
CONSTRAINT FK_NUM_RESERVA FOREIGN KEY (Num_Reserva) REFERENCES RESERVA(Num_Reserva)
);

CREATE TABLE PLATOS(
Cod_Plato NUMBER(10) PRIMARY KEY,
Nombre VARCHAR2(30) NOT NULL,
Tipo VARCHAR2(15) NOT NULL,
Precio NUMBER (3,2) NOT NULL,
Descripcion VARCHAR2(100) NOT NULL
);

CREATE TABLE PRODUCTOS(
Cod_Producto NUMBER(10) PRIMARY KEY,
Nombre VARCHAR2(30) NOT NULL,
Categoria VARCHAR2(15) NOT NULL,
Precio NUMBER(3,2) NOT NULL,
Unidad VARCHAR2(15) NOT NULL,
Stock NUMBER(4) NOT NULL
);

CREATE TABLE PLATO_PRODUCTOS(
Cod_Plato NUMBER(10) NOT NULL,
Cod_Producto NUMBER(10) NOT NULL,
CONSTRAINT FK_COD_PLATO FOREIGN KEY (Cod_Plato) REFERENCES PLATOS(Cod_Plato),
CONSTRAINT FK_COD_PRODUCTO FOREIGN KEY (Cod_Producto) REFERENCES PRODUCTOS(Cod_Producto)
);

CREATE TABLE PROVEEDORES(
Cod_Proveedor NUMBER(10) PRIMARY KEY,
Nombre VARCHAR2(20) NOT NULL,
Direccion VARCHAR2(50) NOT NULL,
Cod_Postal NUMBER(5) NOT NULL,
Telefono NUMBER(9) NOT NULL,
Fax NUMBER(9) NOT NULL,
Persona_Contacto VARCHAR2(20) NOT NULL
);

CREATE TABLE PROVEEDORES_PRODUCTO (
Cod_Proveedor NUMBER(10) NOT NULL,
Cod_Producto NUMBER(10) NOT NULL,
CONSTRAINT FK_COD_PROVEEDOR FOREIGN KEY (Cod_Proveedor) REFERENCES PROVEEDORES(Cod_Proveedor),
CONSTRAINT FK_COD_PRODUCTO_PROVEEDOR FOREIGN KEY (Cod_Producto) REFERENCES PRODUCTOS(Cod_Producto)
);

CREATE TABLE FACTURA(
Num_Factura NUMBER(10) PRIMARY KEY,
Fecha_Factura DATE NOT NULL,
Id_Mesa NUMBER(10) NOT NULL,
Cod_Plato NUMBER(10) NOT NULL,
CONSTRAINT FK_NUMERO_MESA FOREIGN KEY (Id_Mesa) REFERENCES MESAS(Id_Mesa),
CONSTRAINT FK_COD_PLATO_FACT FOREIGN KEY (Cod_Plato) REFERENCES PLATOS(Cod_Plato)
);

CREATE TABLE FACTURA_CONTIENE_PLATOS(
Num_Factura NUMBER (10) NOT NULL,
Cod_Plato NUMBER (10) NOT NULL,
Unidades NUMBER (3) NOT NULL, 
Importe NUMBER (3,2) NOT NULL,
CONSTRAINT FK_NUM_FACTURA FOREIGN KEY (Num_Factura) REFERENCES FACTURA(Num_Factura),
CONSTRAINT FK_PLATO FOREIGN KEY (Cod_Plato) REFERENCES PLATOS(Cod_Plato)
);

CREATE TABLE IMPORTE_TOTAL(
Num_Factura NUMBER(10) NOT NULL,
Importe_Total NUMBER(4,2) NOT NULL,
CONSTRAINT FK_NUM_FACTURA_IMPORTE FOREIGN KEY (Num_Factura) REFERENCES FACTURA(Num_Factura)
);

CREATE UNIQUE INDEX IDX_Empleados_Nombre_Apellidos
ON EMPLEADO (Nombre, Apellidos);

ALTER TABLE EMPLEADO
ADD CONSTRAINT CK_Fecha_Alta CHECK (Fecha_Alta >= TO_DATE ('01-06-2022', 'DD-MM-YYYY'));


ALTER TABLE CAMAREROS
ADD CONSTRAINT CK_Turno CHECK (Turno IN ('mañana', 'tarde', 'noche'));

DROP TABLE PROVEEDORES;

CREATE TABLE PROVEEDORES(
Cod_Proveedor NUMBER(10) PRIMARY KEY,
Nombre VARCHAR2(20) NOT NULL,
Apellidos VARCHAR2(50) NOT NULL,
Direccion VARCHAR2(50) NOT NULL,
Cod_Postal NUMBER(5) NOT NULL,
Telefono NUMBER(9) NOT NULL,
Fax NUMBER(9) NOT NULL,
Persona_Contacto VARCHAR2(20) NOT NULL
);

ALTER TABLE MESAS
MODIFY Num_Asientos INT DEFAULT 4;

CREATE INDEX IDX_CATEGORIA ON PRODUCTOS (Categoria);
SELECT INDEX_NAME FROM ALL_INDEXES WHERE TABLE_NAME = 'PRODUCTOS';

ALTER TABLE PRODUCTOS
MODIFY Stock INT;

ALTER TABLE PRODUCTOS
ADD CONSTRAINT CHK_STOCK CHECK (Stock IS NOT NULL AND Stock >= 0 AND Stock < 10000);

DROP INDEX idx_categoria;

ALTER TABLE PROVEEDORES_PRODUCTO
DROP CONSTRAINT FK_COD_PROVEEDOR;

DROP TABLE PROVEEDORES;

DROP USER c##restaurante CASCADE;

