/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.relojdigital;

import java.util.Date;

/**
 *
 * @author David
 */
public class PanelAlarma extends javax.swing.JPanel {

    /**
     * Creates new form PanelAlarma
     */
    public PanelAlarma() {
        
        initComponents();
        SpinnerAlarma.setValue(new Date());
        chkBoxActiva.setSelected(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        SpinnerAlarma = new javax.swing.JSpinner();
        chkBoxActiva = new javax.swing.JCheckBox();

        jLabel1.setText("Hora alarma:");

        SpinnerAlarma.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(), null, null, java.util.Calendar.AM_PM));
        SpinnerAlarma.setDoubleBuffered(true);
        SpinnerAlarma.setEditor(new javax.swing.JSpinner.DateEditor(SpinnerAlarma, "HH:mm"));

        chkBoxActiva.setText("Activa");
        chkBoxActiva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkBoxActivaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(37, 37, 37)
                .addComponent(SpinnerAlarma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(chkBoxActiva)
                .addContainerGap(88, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(SpinnerAlarma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chkBoxActiva))
                .addContainerGap(112, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void chkBoxActivaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkBoxActivaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkBoxActivaActionPerformed


    public Alarma obtenerDatosAlarma(){
    
        Date date = (Date) SpinnerAlarma.getValue();
        boolean activa = chkBoxActiva.isSelected();
        return new Alarma(date, activa);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner SpinnerAlarma;
    private javax.swing.JCheckBox chkBoxActiva;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
