CREATE TABLE ALUMNO(
Dni_Alumno VARCHAR2(9) PRIMARY KEY NOT NULL,
Nombre VARCHAR2 NOT NULL,
Apellidos VARCHAR2 NOT NULL,
Direccion VARCHAR2 NOT NULL,
Municipio VARCHAR2 NOT NULL,
Provincia VARCHAR2 NOT NULL,
Cod_Postal NUMBER(5,0) NOT NULL,
Email VARCHAR2 NOT NULL,
Telefono NUMBER (9,0) NOT NULL,
Fecha_Nacimiento DATE NOT NULL

);

CREATE TABLE TUTOR(
Dni_Tutor VARCHAR2(9) PRIMARY KEY NOT NULL,
Nombre VARCHAR2 NOT NULL,
Apellidos VARCHAR2 NOT NULL,
Email VARCHAR2 NOT NULL,
Teléfono NUMBER(9) NOT NULL

);


CREATE TABLE PROYECTO(
Titulo VARCHAR2 PRIMARY KEY NOT NULL,
Descripcion VARCHAR NOT NULL,
Nota NUMBER NOT NULL,
Fecha_Presentacion DATE NOT NULL

);

CREATE TABLE EMPRESA(
Cif VARCHAR(9) PRIMARY KEY NOT NULL,
Nombre VARCHAR NOT NULL,
Direccion VARCHAR NOT NULL,
Municipio VARCHAR2 NOT NULL,
Provincia VARCHAR2 NOT NULL,
Cod_Postal NUMBER(5,0) NOT NULL,
Num_Convenio NUMBER NOT NULL,
Email VARCHAR NOT NULL,
Telefono NUMBER(9) NOT NULL,
Web VARCHAR NOT NULL

);

