package clasesDB;
// Generated 14 ene 2024 22:38:20 by Hibernate Tools 6.3.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Departamentos generated by hbm2java
 */
public class Departamentos implements java.io.Serializable {

	private Integer deptNo;
	private String dnombre;
	private Set empleadoses = new HashSet(0);

	public Departamentos() {
	}

	public Departamentos(String dnombre, Set empleadoses) {
		this.dnombre = dnombre;
		this.empleadoses = empleadoses;
	}

	public Integer getDeptNo() {
		return this.deptNo;
	}

	public void setDeptNo(Integer deptNo) {
		this.deptNo = deptNo;
	}

	public String getDnombre() {
		return this.dnombre;
	}

	public void setDnombre(String dnombre) {
		this.dnombre = dnombre;
	}

	public Set getEmpleadoses() {
		return this.empleadoses;
	}

	public void setEmpleadoses(Set empleadoses) {
		this.empleadoses = empleadoses;
	}

}
