/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Formularios;

/**
 *
 * @author David
 */
public class HacerReserva extends javax.swing.JDialog {

    /**
     * Creates new form HacerReserva
     */
    public HacerReserva(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jtextNombre = new javax.swing.JTextField();
        jtextContacto = new javax.swing.JTextField();
        jspinnerFecha = new javax.swing.JSpinner();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jbtnBanquete = new javax.swing.JRadioButton();
        jbtnJornada = new javax.swing.JRadioButton();
        jbtnCongreso = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jspinnerPersonas = new javax.swing.JSpinner();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jlistTipoCocina = new javax.swing.JList<>();
        jLabel8 = new javax.swing.JLabel();
        jspinnerJornadas = new javax.swing.JSpinner();
        jchkbxHabitaciones = new javax.swing.JCheckBox();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setText("Fecha del evento:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, -1, -1));

        jLabel3.setText("Teléfono de contacto:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 60, -1, -1));

        jLabel5.setText("Nombre:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, -1, -1));

        jtextNombre.setToolTipText("Indique su nombre y apellidos");
        jPanel1.add(jtextNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 90, -1));

        jtextContacto.setToolTipText("Indique su número de teléfono");
        jPanel1.add(jtextContacto, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 60, 100, -1));

        jspinnerFecha.setModel(new javax.swing.SpinnerDateModel());
        jspinnerFecha.setToolTipText("Indique la fecha y hora en la que se realizará el evento");
        jPanel1.add(jspinnerFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 100, -1, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 510, 10));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("FORMULARIO DE RESERVA");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, -1, -1));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Tipo"));
        jPanel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        buttonGroup1.add(jbtnBanquete);
        jbtnBanquete.setText("Banquete");
        jbtnBanquete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBanqueteActionPerformed(evt);
            }
        });

        buttonGroup1.add(jbtnJornada);
        jbtnJornada.setText("Jornada");
        jbtnJornada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnJornadaActionPerformed(evt);
            }
        });

        buttonGroup1.add(jbtnCongreso);
        jbtnCongreso.setText("Congreso");
        jbtnCongreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCongresoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jbtnBanquete)
                .addGap(18, 18, 18)
                .addComponent(jbtnJornada)
                .addGap(18, 18, 18)
                .addComponent(jbtnCongreso)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnBanquete)
                    .addComponent(jbtnJornada)
                    .addComponent(jbtnCongreso))
                .addGap(0, 6, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, -1, 50));

        jLabel2.setText("Número de personas:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, -1, -1));

        jspinnerPersonas.setToolTipText("Indique el número de personas que acudirán al evento");
        jPanel1.add(jspinnerPersonas, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, -1, -1));

        jLabel7.setText("Tipo de cocina:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 190, -1, -1));

        jlistTipoCocina.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Bufé", "Carta", "Pedir cita con el chef", "No precisa" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jlistTipoCocina.setToolTipText("Indique que tipo de cocina quiere escoger");
        jScrollPane1.setViewportView(jlistTipoCocina);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 190, 150, 40));

        jLabel8.setText("Número de jornadas:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, -1, -1));

        jspinnerJornadas.setToolTipText("Indique el número de jornadas");
        jPanel1.add(jspinnerJornadas, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 260, -1, -1));

        jchkbxHabitaciones.setText("Requerirá habitaciones");
        jchkbxHabitaciones.setToolTipText("Marque si requerirá habitaciones");
        jPanel1.add(jchkbxHabitaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 260, -1, -1));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 510, 10));

        jLabel1.setBackground(new java.awt.Color(245, 20, 20));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 310));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Activar seleccionar número de jornadas y si requiere habitaciones solo cuando se selecciona Congreso.
    private void jbtnCongresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCongresoActionPerformed
        // TODO add your handling code here:
                jspinnerJornadas.setEnabled(true);
                jchkbxHabitaciones.setEnabled(true);
    }//GEN-LAST:event_jbtnCongresoActionPerformed

         
    private void jbtnBanqueteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBanqueteActionPerformed
                jspinnerJornadas.setEnabled(false);
                jchkbxHabitaciones.setEnabled(false);
    }//GEN-LAST:event_jbtnBanqueteActionPerformed

    private void jbtnJornadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnJornadaActionPerformed
        // TODO add your handling code here:
                jspinnerJornadas.setEnabled(false);
                jchkbxHabitaciones.setEnabled(false);
    }//GEN-LAST:event_jbtnJornadaActionPerformed

  
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JRadioButton jbtnBanquete;
    private javax.swing.JRadioButton jbtnCongreso;
    private javax.swing.JRadioButton jbtnJornada;
    private javax.swing.JCheckBox jchkbxHabitaciones;
    private javax.swing.JList<String> jlistTipoCocina;
    private javax.swing.JSpinner jspinnerFecha;
    private javax.swing.JSpinner jspinnerJornadas;
    private javax.swing.JSpinner jspinnerPersonas;
    private javax.swing.JTextField jtextContacto;
    private javax.swing.JTextField jtextNombre;
    // End of variables declaration//GEN-END:variables
}
